package com.spoj.test;

import static org.junit.Assert.assertEquals;

import org.junit.jupiter.api.Test;

public class EditDistance {

	@Test
	void test1() {
		assertEquals(2, com.spoj.impl.EditDistance.counter("AB", "BAA"));
	}
	
	@Test
	void test2() {
		assertEquals(7, com.spoj.impl.EditDistance.counter("ALLAHABAD", "YATINDRA"));
	}
	
	@Test
	void test3() {
		assertEquals(3, com.spoj.impl.EditDistance.counter("SATURDAY", "SUNDAY"));
	}

	@Test
	void test4() {
		assertEquals(4, com.spoj.impl.EditDistance.counter("qwert", "ertqw"));
	}

	@Test
	void test5() {
		assertEquals(56, com.spoj.impl.EditDistance.counter(
				"AAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"));
	}
	
	@Test
	void test6() {
		assertEquals(4, com.spoj.impl.EditDistance.counter("", ""));
	}
}
